#!/bin/sh
# auto/config — invocado por 'lb config'. Define parámetros de la build.
# Ubicación convencional: <build_root>/auto/config (NO dentro de config/).

set -e

lb config noauto \
    --mode ubuntu \
    --distribution noble \
    --archive-areas "main restricted universe multiverse" \
    --linux-flavours generic \
    --binary-images iso-hybrid \
    --debian-installer false \
    --apt-indices false \
    --memtest none \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "PatrickOS Alpha" \
    --iso-publisher "Patrick Mendoza" \
    --iso-volume "PatrickOS Alpha" \
    "${@}"
